export const WALLET_OK = 'WALLET_OK';
export const WALLET_LOADING = 'WALLET_LOADING';
export const WALLET_ERROR = 'WALLET_ERROR';
export const CONTROLLER_CHANGE_AMOUNT = 'CONTROLLER_CHANGE_AMOUNT';
export const CONTROLLER_SELECT_NETWORK = 'CONTROLLER_SELECT_NETWORK';
export const CONTROLLER_SELECT_STABLECOIN = 'CONTROLLER_SELECT_STABLECOIN';
