export const WALLET_OK = 'WALLET_OK';
export const WALLET_LOADING = 'WALLET_LOADING';
export const WALLET_ERROR = 'WALLET_ERROR';
export const CONTROLLER_CHANGE_AMOUNT = 'CONTROLLER_CHANGE_AMOUNT';
export const CONTROLLER_SELECT_NETWORK = 'CONTROLLER_SELECT_NETWORK';
export const CONTROLLER_SELECT_COIN = 'CONTROLLER_SELECT_COIN';
export const CONTROLLER_CHANGE_APP_SCREEN = 'CONTROLLER_CHANGE_APP_SCREEN';
export const CONTROLLER_UPDATE_NOTIFICATION = 'CONTROLLER_UPDATE_NOTIFICATION';

